### ISSUE TITLE
Realizar marcação de resumo nas bases do GIM

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/MarkAbstract#11]
Lembrar que LILACS já está marcada

**Comment by heitorbarbieri** [comment]
@botturam, a biblioteca do MarkAbstract foi atualizada.  Favor verificar o comportamento no próximo processamento dos arquivos xml. Não sei se o processamento atual já incorpora os arquivos xml do GIM.

**Comment by renatomurasaki** [comment]
@heitorbarbieri @botturam creio que está funcionando, conforme exemplo abaixo, ou o resumo veio marcado por conta do enriquecimento de dados do Medline?

https://search.bvsalud.org/global-literature-on-novel-coronavirus-2019-ncov/resource/en/covidwhomdl-32332514

**Comment by botturam** [comment]
Sim. Está funcionando por ser um doc MEDLINE. LILACS tb funciona em GIM. As demais, precisamos testar.

**Comment by botturam** [comment]
processamento regular em produção regular. Vem sendo executado há 1 ano, com frequente feedback ao Heitor.
