### ISSUE TITLE
Verificar a possibilidade de reconhecer as seções com o delimitador ". "

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/MarkAbstract#3]
Os resumos do PAHO IRIS estão delimitando os tokens com ". "

**Comment by heitorbarbieri** [comment]
Foram identificadas duas situações onde deveriam ocorrer marcações:
  1) O caso onde no ínicio de sentença ocorrem uma ou mais palavras seguidas do caracter ':'
        - verifica se ocorrem 3 ou mais casos e checam-se as palavras contra um grupo de palavras pré-definidas
  2) O caso onde no ínicio de sentença ocorre uma única palavra seguida do caracter ':' ou '.'
        - só verifica se a palavra pertence a um segundo grupo de palavras pré-definidas.

 O algorítmo tenta verificar se o primeiro caso ocorre, neste caso executa a marcação tradicional. Se não, verifica se o segundo caso ocorre e neste caso executa outro algoritmo de marcação. Se nenhum dos dois casos ocorre, então não se marca o texto.
